In [ ]:
import numpy as np

In [ ]:
mtz = np.array([[1,2,3],[4,5,6], [7,8,9]])

print(mtz)

print()

# buscando uma linha da matriz
print(mtz[0])

print()

# buscando múltiplas linhas
print(mtz[0:2])

# buscando colunas
print()

# print(mtz[linhas, colunas])
# print(mtz[inclusivo:exclusivo, inclusivo:exclusivo])
print(mtz[:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [4 5]
 [7 8]]


**Condições**

In [ ]:
print(mtz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
filter = mtz > 5

print(filter)

print(mtz[filter])

filter = mtz % 2 == 0

print(filter)
print(mtz[filter])

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


**Trabalhando com padrões textuais**

In [ ]:
arr = np.array(['Python', 'NumPy', 'Pandas', 'MatPlot8uLib', 'Ciencia de Dados'])

In [ ]:
print(arr)

['Python' 'NumPy' 'Pandas' 'MatPlotLib' 'Ciencia de Dados']


In [ ]:
print(np.char.find(arr, 'u'))

[-1  1 -1  7 -1]


In [ ]:
print(np.char.startswith(arr, 'P'))

[ True False  True False False]


In [ ]:
print(np.char.upper(arr))

['PYTHON' 'NUMPY' 'PANDAS' 'MATPLOTULIB' 'CIENCIA DE DADOS']


In [ ]:
print(np.char.isalpha(arr))

[ True  True  True False False]


**Impotando arquivo de teste**

In [ ]:
dataset = np.loadtxt('/content/arquivo.txt', delimiter=',', dtype=str)
print(f'TXT: {dataset}')

np.savetxt('Arquivo1.txt', dataset, fmt='%s')

np.save('Arquivo1.npy', dataset)

dataset1 = np.load('Arquivo1.npy')
print(f'NPY: {dataset1}')

TXT: ['Python' 'Pandas' 'NumPy' 'MatPlotLib' 'Data Science']
NPY: ['Python' 'Pandas' 'NumPy' 'MatPlotLib' 'Data Science']


**Importando dados de um dataset real!!**

In [ ]:
dataset = np.loadtxt('space.csv', delimiter=';', dtype=str, encoding='utf-8')

print(len(dataset))

header = dataset[0]
body = dataset[1:]

# print(body)

filter = dataset[:, 1] == 'SpaceX'
SpaceX = dataset[filter]

print(SpaceX)



4325
[['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA'
  'Fri Aug 07 2020 05:12 UTC'
  'Falcon 9 Block 5 | Starlink V1 L9 & BlackSky' 'StatusActive' '50.0 '
  'Success']
 ['2' 'SpaceX' 'Pad A Boca Chica Texas USA' 'Tue Aug 04 2020 23:57 UTC'
  'Starship Prototype | 150 Meter Hop' 'StatusActive' '0' 'Success']
 ['8' 'SpaceX' 'SLC-40 Cape Canaveral AFS Florida USA'
  'Mon Jul 20 2020 21:30 UTC' 'Falcon 9 Block 5 | ANASIS-II'
  'StatusActive' '50.0 ' 'Success']
 ['17' 'SpaceX' 'SLC-40 Cape Canaveral AFS Florida USA'
  'Tue Jun 30 2020 20:10 UTC' 'Falcon 9 Block 5 | GPS III SV03'
  'StatusActive' '50.0 ' 'Success']
 ['20' 'SpaceX' 'SLC-40 Cape Canaveral AFS Florida USA'
  'Sat Jun 13 2020 09:21 UTC'
  'Falcon 9 Block 5 | Starlink V1 L8 & SkySat 16 to 18' 'StatusActive'
  '50.0 ' 'Success']
 ['23' 'SpaceX' 'SLC-40 Cape Canaveral AFS Florida USA'
  'Thu Jun 04 2020 01:25 UTC' 'Falcon 9 Block 5 | Starlink V1 L7'
  'StatusActive' '50.0 ' 'Success']
 ['25' 'SpaceX' 'LC-39A Kennedy Space 