In [ ]:
import numpy as np

**Array unidimensional**

In [ ]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


**Array bidimensional**


In [ ]:
matriz = np.array([[1,2,3], [4,5,6],[7,8,9]])

print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**array de zero e um**

In [ ]:
arr = np.zeros(10)
print(arr)

matriz = np.zeros([3,5])
print(matriz)

print()

arr = np.ones(5)
print(arr)

matriz = np.ones([5,3])
print(matriz)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Operações básicas**

In [ ]:
arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(f'Valor mínimo: {arr.min()}, índice: {arr.argmin()}')
print(f'Valor máximo: {arr.max()}, índice: {arr.argmax()}')

Valor mínimo: 1, índice: 0
Valor máximo: 4, índice: 3


In [ ]:
# Exemplo Extra com trigonometria, mostrando a superioridade do numpy trabalhando com arrays e não somente com scalar necessitando de um loop tradicional e pouco performático
x = 1
y = 5

distancia_cm =np.hypot(x, y) * 100
angulo_graus = np.degrees(np.arctan2(y,x))

print(distancia_cm)
print(angulo_graus)

print()
import math

dist = math.sqrt(x**2 + y**2)*100
angulo = math.atan2(y,x)*(180/math.pi)
print(dist)
print(angulo)

509.9019513592784
78.69006752597979

509.9019513592784
78.69006752597979


In [ ]:
print(f'Soma: {arr.sum()}, média: {arr.mean()}')
print(arr)
arr2 = np.array([5,6,7,8])
print(arr2)

print(f"Soma índice a índice: {arr + arr2}")
print(f'Multiplicação índice a índice: {arr * arr2}')
print(f' Juntar dois arrays: {np.concatenate((arr, arr2))}')

Soma: 10, média: 2.5
[1 2 3 4]
[5 6 7 8]
Soma índice a índice: [ 6  8 10 12]
Multiplicação índice a índice: [ 5 12 21 32]
 Juntar dois arrays: [1 2 3 4 5 6 7 8]


**Remodelando forma do array**

In [ ]:
arr = np.arange(9)
print(arr)

print()

matriz = arr.reshape([3,3])  # Precisa ter o mesmo tamanho do array unidimensional
print(matriz)

print()
print(f'Tamanho array: {matriz.size}')
print(f'Quantidade de dimensões: {matriz.ndim}')
print(f'Qual o corpo, modelo do array? {matriz.shape}')
print(f'Soma das colunas: {matriz.sum(axis=0)}')
print(f'Soma das linhas: {matriz.sum(axis=1)}')
print('Operações entre matriz e um valor escalar (Broadcast):')
print(matriz*5)
print()
print(matriz/2)
print()
print(matriz-5)

[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Tamanho array: 9
Quantidade de dimensões: 2
Qual o corpo, modelo do array? (3, 3)
Soma das colunas: [ 9 12 15]
Soma das linhas: [ 3 12 21]
Operações entre matriz e um valor escalar (Broadcast):
[[ 0  5 10]
 [15 20 25]
 [30 35 40]]

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]

[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]


**Números aleatórios**

In [ ]:
np.random.seed(5)

arr = np.random.randint(0, 10, 10)
print(arr)

matriz = np.random.randint(0, 10, [5, 5])
print(matriz)

[3 6 6 0 9 8 4 7 0 0]
[[7 1 5 7 0]
 [1 4 6 2 9]
 [9 9 9 1 2]
 [7 0 5 0 0]
 [4 4 9 3 2]]


**Identifica únicos e conta recoreências de repetições**

In [ ]:
arr = np.array([1,2, 2, 3, 3, 4])

print(np.unique(arr))

print(np.unique(arr, return_counts=True))



[1 2 3 4]
(array([1, 2, 3, 4]), array([1, 2, 2, 1]))
